### ISSUE TITLE
KP on Mojave 10.14.4

### ISSUE THREAD

**Issue by christophcharles** [chris1111/GenericBrightness#1]
I am using this kext on a laptop that uses OEM ACPI methods for brightness control. It broke with Mojave 10.14.4 update by causing a KP on boot. The kext loads fine when using kextload manually.

On my computer, the issue is resolved by correctly initializing `displayRes` in `GenericBrightness::getDisplay` to `NULL`.  My guess is that `getMatchingServices` fails now in the boot process leading to garbage being returned from the function.

The corrected code can be found here: https://github.com/christophcharles/GenericBrightness/blob/master/GenericBrightness.cpp

**Comment by chris1111** [comment]
Thanks for the catch
